spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/calculator
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  path: api
  version: v1

app:
  jwt:
    secret-key: any-secret-key h256
    expiration: 86400000 #default as a day
  random-string:
    client-uri: https://api.random.org/json-rpc/4/invoke
    api-key: your-key-from-random-org
